/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componentesswing;

/**
 *
 * @author erandi
 */
public class DesactivacionBotones extends javax.swing.JFrame {

    /**
     * Creates new form DesactivacionBotones
     */
    public DesactivacionBotones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDesactiva = new javax.swing.JButton();
        btnEstrella = new javax.swing.JButton();
        btnActiva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDesactiva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/manitaIzq.png"))); // NOI18N
        btnDesactiva.setText("Desactiva boton");
        btnDesactiva.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnDesactiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesactivaActionPerformed(evt);
            }
        });

        btnEstrella.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/star3.png"))); // NOI18N
        btnEstrella.setEnabled(false);

        btnActiva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/manitaDer.png"))); // NOI18N
        btnActiva.setText("Activa boton");
        btnActiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDesactiva, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnEstrella, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnActiva, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnDesactiva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEstrella, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(btnActiva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDesactivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactivaActionPerformed
    if (!("Activa boton".equals(evt.getActionCommand()))) { //¿boton 1 no esta deshabilitado?
        System.out.println("events "+evt.getActionCommand());
        btnDesactiva.setEnabled(true); //no habilites
        btnEstrella.setEnabled(false); //no habilites
        btnActiva.setEnabled(true);  //habilita
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDesactivaActionPerformed

    private void btnActivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivaActionPerformed
    System.out.println("events "+evt.getActionCommand());
        if (!("Desactiva boton".equals(evt.getActionCommand()))) {//¿boton 3 no esta deshabilitado?
        
        btnDesactiva.setEnabled(true);   //habilita
        btnEstrella.setEnabled(true);   //habilita
        btnActiva.setEnabled(true);  //deshabilitado 
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActivaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesactivacionBotones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesactivacionBotones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesactivacionBotones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesactivacionBotones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DesactivacionBotones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActiva;
    private javax.swing.JButton btnDesactiva;
    private javax.swing.JButton btnEstrella;
    // End of variables declaration//GEN-END:variables
}
