/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componentesswing;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author erandi
 */
public class MessageDialog extends javax.swing.JFrame {

    /**
     * Creates new form MessageDialog
     */
    public MessageDialog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnOp1 = new javax.swing.JButton();
        btnOp2 = new javax.swing.JButton();
        btnOp3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnOp4 = new javax.swing.JButton();
        btnOp5 = new javax.swing.JButton();
        btnOp6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnOp7 = new javax.swing.JButton();
        btnOp8 = new javax.swing.JButton();
        btnOp9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Show Message Dialog"));

        btnOp1.setText("Opción 1");
        btnOp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOp1ActionPerformed(evt);
            }
        });

        btnOp2.setText("Opción 2");
        btnOp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOp2ActionPerformed(evt);
            }
        });

        btnOp3.setText("Opción 3");
        btnOp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOp3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnOp1)
                .addGap(18, 18, 18)
                .addComponent(btnOp2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOp3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOp1)
                    .addComponent(btnOp2)
                    .addComponent(btnOp3))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Message Dialog"));

        btnOp4.setText("Opción 4");
        btnOp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOp4ActionPerformed(evt);
            }
        });

        btnOp5.setText("Opción 5");
        btnOp5.setToolTipText("");
        btnOp5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOp5ActionPerformed(evt);
            }
        });

        btnOp6.setText("Opción 6");
        btnOp6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOp6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnOp4)
                .addGap(26, 26, 26)
                .addComponent(btnOp5)
                .addGap(18, 18, 18)
                .addComponent(btnOp6)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOp4)
                    .addComponent(btnOp5)
                    .addComponent(btnOp6))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("ShowConfirmDialog"));

        btnOp7.setText("Opcion 7");
        btnOp7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOp7ActionPerformed(evt);
            }
        });

        btnOp8.setText("Opción 8");
        btnOp8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOp8ActionPerformed(evt);
            }
        });

        btnOp9.setText("Opción 9");
        btnOp9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOp9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnOp7)
                .addGap(18, 18, 18)
                .addComponent(btnOp8)
                .addGap(29, 29, 29)
                .addComponent(btnOp9)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOp7)
                    .addComponent(btnOp8)
                    .addComponent(btnOp9))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOp1ActionPerformed
        JOptionPane.showMessageDialog(null, "Operación realizada correctamente");
        
        //1. componente padre
        //2. mensaje
    }//GEN-LAST:event_btnOp1ActionPerformed

    private void btnOp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOp2ActionPerformed
        JOptionPane.showMessageDialog(null, "Mensaje dentro de la ventana",
                "Mensaje en la barra de titulo", JOptionPane.WARNING_MESSAGE);
         //1. componente padre
        //2. mensaje
        //3. titulo
        //4. icono 
    }//GEN-LAST:event_btnOp2ActionPerformed

    private void btnOp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOp3ActionPerformed
      
      //  Image image = new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage();  
      //  this.setIconImage(image);
        MyIcon icon = new MyIcon();
        JOptionPane.showMessageDialog(null, "Mensaje dentro de la ventana",
                "Titulo", JOptionPane.DEFAULT_OPTION,icon);

    }//GEN-LAST:event_btnOp3ActionPerformed

    private void btnOp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOp4ActionPerformed
String respuesta = JOptionPane.showInputDialog("Escribe tu nombre");        // texto interno
//String respuesta = JOptionPane.showInputDialog("¿Cual es su nombre?", "atxy2k");  //con texto inicial
//String respuesta = JOptionPane.showInputDialog(null, "Escribe tu nombre"); //indica el componente padre

        System.out.println("respuesta"+ respuesta);
    }//GEN-LAST:event_btnOp4ActionPerformed

    private void btnOp5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOp5ActionPerformed
        String respuesta = JOptionPane.showInputDialog(null, 
        "Escriba nuevamente su nombre", "Error!", JOptionPane.ERROR_MESSAGE);
        System.out.println("respuesta" + respuesta);
    }//GEN-LAST:event_btnOp5ActionPerformed

    private void btnOp6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOp6ActionPerformed
        String[] carreras = {
            "Ingeniería en sistemas computacionales",
            "Ingeniería industrial",
            "Ingeniería en mecatrónica",
            "Ingeniería en informatica",
            "Ingeniería petroquímica"
        };
        MyIcon icon = new MyIcon();
        String resp = (String) JOptionPane.showInputDialog(null, "Seleccione una carrera a cursar", 
                "Carrera", JOptionPane.DEFAULT_OPTION, icon, carreras, carreras[0]);
        System.out.println("respuesta"+ resp); 
    }//GEN-LAST:event_btnOp6ActionPerformed

    private void btnOp7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOp7ActionPerformed
        //int resp = JOptionPane.showConfirmDialog(null, "¿Está seguro?");  
        //cuarto parametro es el tipo de respuesta que puede dar
        int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro?",
                "Alerta!", JOptionPane.YES_NO_OPTION);
         
        System.out.println("respuesta "+ resp);
    }//GEN-LAST:event_btnOp7ActionPerformed

    private void btnOp9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOp9ActionPerformed
    MyIcon icon = new MyIcon();
    String[] options = {"Opcion A", "Opcion B", "Opcion C", "Opcion D"};
    int seleccion = JOptionPane.showOptionDialog(null, "Es necesario que seleccione una opcion", 
            "Titulo", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, icon, options, options[0]); 
    System.out.println("respuesta "+ seleccion);
    }//GEN-LAST:event_btnOp9ActionPerformed

    private void btnOp8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOp8ActionPerformed
         //se agrega icono
        int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro?", "Alerta!",
                JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        System.out.println("respuesta "+ resp);
    }//GEN-LAST:event_btnOp8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MessageDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MessageDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MessageDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MessageDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MessageDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOp1;
    private javax.swing.JButton btnOp2;
    private javax.swing.JButton btnOp3;
    private javax.swing.JButton btnOp4;
    private javax.swing.JButton btnOp5;
    private javax.swing.JButton btnOp6;
    private javax.swing.JButton btnOp7;
    private javax.swing.JButton btnOp8;
    private javax.swing.JButton btnOp9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
