/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hilos2;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author erandi
 */
public class LienzoPelota extends javax.swing.JPanel implements Runnable {

    /**
     * Creates new form LienzoPelota
     */
    Thread hilo;
    //se mueve de forma horizontal
    int x = getWidth()/ 2; //inicializada a la mitad de lienzo
    public LienzoPelota() {
        initComponents();
        hilo = new Thread(this);
    }

    public void paint (Graphics g){
        //cuando se inicie la animación no se vuelva a repetir la imagen en el lienzo
        g.setColor(getBackground()); //para que se vuelva a pintar la imagen
        g.fillRect(0,0,getWidth(),getHeight()); //ovalo con el ancho y algo del panel
        
        g.setColor(Color.red);//color de la pelota
        g.fillOval(x, getHeight()/2,30, 30);  //dibuja la pelota en la posición X a la mitad del lienzo
                                             //altura y ancho constante 30
    }
    
    public void inicio (){
        hilo.start();
    
    }
    
    public void pausa(){
        hilo.suspend();
    }
    
    public void continuar(){
        hilo.resume();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
   //como solo es un hilo conviene el runnable
    @Override
    public void run() {  //animación
           try {
               while(true ){
                    while(x<getWidth()-30){ //mueve a la derecha  
                        Thread.sleep(50);  //contrala la velocidad de la animación
                        x+=10;             //se mueve en escala de 10
                        repaint();        //repinte
                    }
                    while(x>10){            //mueva a la izquierda,impresión uqe toca la pared
                        Thread.sleep(50);
                        x-=10;
                        repaint();
                    }
               
               }
        } catch (Exception e) {
               System.out.println("Sucedion un error"+e.getMessage());
        }
 
    }
}
