/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hilos2;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.geom.Ellipse2D;

/**
 *
 * @author erandi
 */
public class LienzoPelota2 extends javax.swing.JPanel implements Runnable {
    int x=0,y=0, velX=2,velY=2;
    
     Thread hilo,hilo2;
     
    public void paint(Graphics g ){
         g.setColor(getBackground());
         g.fillRect(0,0,getWidth(),getHeight());
         System.out.println("width "+getWidth() + " height "+getHeight());
         g.setColor(Color.BLUE);
         g.fillOval(x, y,40, 40);
       // Ellipse2D circle= new Ellipse2D.Double(x,y,40,40);
        
        
    
    }
    /**
     * Creates new form LienzoPelota2
     */
    public LienzoPelota2() {
        initComponents();
         hilo = new Thread(this);
         hilo2 = new Thread(this);
    }
 public void inicio (){
        hilo.start();
        hilo2.start();
    
    }
    
    public void pausa(){
        hilo.suspend();
        hilo2.suspend();
    }
    
    public void continuar(){
        hilo.resume();
        hilo2.resume();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
       try {
               while(true ){
                
                   if(x<(getWidth()-40) || y<(getHeight()-40)){
                    Thread.sleep(50);
                        x+=velX;             //se mueve en escala de 10
                        y+=velY;
                        System.out.println("!! x: "+x  +"y: "+y );
                        
                        repaint();
                   }
                    if(x<=0||x>=getWidth()-40){
                  
                    velX= -velX;
                    System.out.println("--");
                    }
                    if(y<=0||y>=getHeight()-40){
                       velY= -velY;
                       System.out.println("**");
                   }
            
               
               }
        } catch (Exception e) {
               System.out.println("Sucedion un error"+e.getMessage());
        }
    }
}
